# Generated by Django 4.1.7 on 2023-04-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='news', max_length=254)),
                ('site', models.URLField(unique=True)),
            ],
            options={
                'db_table': 'news_sites',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('url', models.URLField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('text', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_news', to='news.sourcenews')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
