# Generated by Django 4.1.7 on 2023-04-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_sourcenews_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-added_at'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
