# Generated by Django 4.1.7 on 2023-04-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_sourcenews_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-added_at'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['added_at'], name='news_added_a_a472f4_idx'),
        ),
    ]
