# Generated by Django 4.1.7 on 2023-05-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options'),
        ('news', '0003_alter_news_options_news_news_added_a_a472f4_idx'),
    ]

    operations = [
    ]
