# Generated by Django 4.1.7 on 2023-06-14 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_merge_20230526_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites_news', to='news.sourcenews'),
        ),
    ]
