# Generated by Django 4.1.5 on 2023-02-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_category_alter_note_options_sitenote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='sitenote',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
