# Generated by Django 4.1.5 on 2023-02-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_category_options_alter_sitenote_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='sitenote',
            options={'ordering': ['created_at', 'title', 'url']},
        ),
        migrations.AddField(
            model_name='sitenote',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
